---
title: The Kidneys Can Tweet?! An Exploratory Analysis of Twitter Hashtags Related
  to CKDu.
author: "Daniel Smith {daniel.smith2@emory.edu} "
date: "2/6/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Overview and Motivation

Being an avid twitter user has showed me the value that global connections can have when discussing research ideas and connecting with other scientists. Applying data analytic techniques to tweets has proven to be a wealth of knowledge for other researchers.  Due to this, I am eager to gain new skills that will allow me to function more proficiently in the world of nursing data science. Thru this project, I will gain insight and knowledge about the current conversations occurring between other scientist in regard to the research behind the current epidemic of chronic kidney disease of unknown etiology (CKDu), which is the focus of my dissertation project with Drs. Hertzberg and Mac. For my dissertation, I am studying the occupational histories and exposures of immigrant patients receiving emergent dialysis in Atlanta, GA, who are hypothesized to suffer from CKDu. By conducting an analysis of tweets related to CKDu, I will gain a more in-depth understanding of this global epidemic that will shape my understanding and thinking of my own dissertation project while, at the same time, helping me to gain new data science skills.


## Project Objectives

This project will seek to characterize tweets about the CKDu epidemic. 
__Q1__. What are the frequencies of hashtags used when tweeting about the CKDu epidemic?
__Q2__. What are the frequencies of keywords used when tweeting abotu the CKDu epidemic?
__Q3__. Where are people from who are tweeting about the CKDu epidemic?
__Q4__. What are the emtions of tweets about the CKDu epidemic? 

By exploring the four questions above, I hope to learn methods for accessing and searching twitter data, cleaning and processing extracted tweets, and analyzing tweets for frequency, location of origin, and sentiment. 

## Data

Using R package 'rtweet' data will be extracted from Twitter.com a social media website that allows users to tweet short messages of 280 characters or less. Common data that can be acquired via tweet analysis includes textual/sentiment analysis, analysis of the social connections between users, and geolocation analysis of where a tweet originated. This project will be focused on analyzing tweets with keywords and hashtags related to the global CKDu epidemic. Currently, candidate key words include 'chronic kidney disease of unknown etiology', 'enfermedad renal crónica no tradicional', 'mesoamerican nephropathy', and 'chronic interstitial nephritis in agricultural communities'. Candidate hastags are #CKDu #CINAC #MeN and #ERCnt. 

## Data Wrangling: 

From what I have seen in the literature thus far, there will be preprocessing of the tweet data required before I can analyze my data. Tweets will need to be converted to lower case letters; usernames, links, punctuation, digits, and stopwords will need to be removed; and stemming of words (i.e. making "walking"", "walk", and "walks"" all appear in the base form of "walk") will have to occur. The R package 'tm' will be used for preprocessing of the data.


## Exploratory Analysis:

Exploratory Analysis will be conducted first with a subset of the total tweets acquired from Twitter. The ‘tm’ package in R will be used to summarize and give frequencies for the keywords and hashtags of the subset of downloaded tweets. Location of origin for the subset will be analyzed using both the ‘ggplot2’ and ‘dplyr’ packages. Simple sentiment analysis (positive vs. negative) will be conducted on this subset using the ‘syuzhet’ package in R.

## Analysis

Once exploratory analysis is completed, the totality of the extracted tweets will be analyzed using similar methods as described above. However, in addition to the simple sentiment analysis (positive vs. negative), eight emotion sentiment analysis (anger, anticipation, disgust, fear, joy, sadness, surprise, and trust) will be conducted to further understand the emotions behind CKDu tweets. 

## Schedule

### Completed Activities

-January 28, 2019 Meeting with Steve Pittard to discuss rTweet package and potential difficulties with analyzing tweets. 

-January 28, 2019 Apply for Twitter Developer Account. A developer account is needed for access to Twitter's API that will allow for tweet extraction and data analysis in R. Developer Account Applicaiton Status: __Approved!__

### Future Activities/Deadlines

-Week of __Feb 11__: Finalize milestone 1 and submit by February 13.

-Week of __Feb 18__: Extract Tweets from Twitter 

-Week of __Feb 25__: No activities scheduled due to SNRS Conference Attendance. 

-Week of __March 4__: Preprocess the subset of tweets to be used in the exploratory analysis. 

-Week of __March 11__: Analyze subset of tweets using the 'tm', 'ggplot2', and 'dplyr' packages to calculate frequencies of hashtags & keywords and to calculate location of origin.

-Week of __March 18__: Analyze subset of tweets for simple sentiment analysis using the ‘syuzhet’ package.

-Week of __March 25__: Finalize milestone 2 and submit by March 27. 

-Week of __April 1__: d 

-Week of __April 8__: 

-Week of __April 15__: 

-Week of __April 22__: 

-Week of __April 29__: Finalized milestone 3 and present project on May 1. 




Keeping in mind the due dates listed above for the intermediate and final milestones, make a plan to meet these deadlines. Write these in terms of weekly tasks / goals.

